#!/bin/bash
#
# Start script for register-api that assumes environment variables are already provided

APP_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PORT=${PORT:=10000}
exec java ${JAVA_MEM_ARGS} -jar -Dserver.port="${PORT}" "${APP_DIR}/test-data-generator.jar"
